name: ulin_atuhfront
description: "Aplikasi panduan wisata Ulin Atuh"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10
  #google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  http: ^1.2.1
  logger: ^2.0.2
  image_picker: ^1.1.2
  dropdown_search: ^5.0.6
  intl: ^0.18.1
  mime: ^1.0.5
  http_parser: ^4.0.2
  provider: ^6.1.2
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/Google_Icons.webp
    - assets/images/jg.jpeg
    - assets/images/caijg.jpeg
    - assets/images/toni.jpeg
    - assets/images/natasa.jpeg
    - assets/images/cris.jpeg
    - assets/images/puncakdamar_thumb1.jpeg
    - assets/images/alkamil_thumb4.jpeg
    - assets/images/profile.png
  

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400